// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "68f45eff-733d-4fb1-9376-28f15b06f39c");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1571572138);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1571573799);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1571572258);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 2888);
user_pref("browser.cache.disk.capacity", 788480);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1571572107);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 86);
user_pref("browser.newtabpage.activity-stream.impressionId", "{9a51bb57-a6b9-49ed-9306-7fef7c1317ee}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1571572167144");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1571573947144");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1571572120978");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1571575720978");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20191002193559");
user_pref("browser.slowStartup.averageTime", 1198);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20191002193559");
user_pref("browser.startup.homepage_override.mstone", "69.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1571573769);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1571573779396");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "69.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "f2fef0f337d740f1969e5cea244cf666");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20191002193559");
user_pref("extensions.lastAppVersion", "69.0.2");
user_pref("extensions.lastPlatformVersion", "69.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"994e1d19-7794-4799-a36b-9f038039c327\",\"fxmonitor@mozilla.org\":\"41613131-2d05-4629-89de-ee051af9dade\",\"screenshots@mozilla.org\":\"da3a2745-e8c5-480f-b9f1-c5ecee75a7e6\",\"webcompat-reporter@mozilla.org\":\"04a23917-9082-4dd6-a668-e7ae26dc1f12\",\"webcompat@mozilla.org\":\"48df7f18-d0aa-4624-8fe3-1da52a7be327\",\"default-theme@mozilla.org\":\"04cb9ab7-3833-489e-9c64-87590f52a620\",\"google@search.mozilla.org\":\"d602816b-e69e-4fca-8358-6b56dd1dd646\",\"amazondotcom@search.mozilla.org\":\"a871fcbb-f2be-4b11-a3bf-78bdf9cf7d06\",\"bing@search.mozilla.org\":\"2d0aa07c-b85b-40cc-b390-2aaadbac734b\",\"ddg@search.mozilla.org\":\"e524a3d0-a3ac-4462-bed5-f7e692111dbf\",\"ebay@search.mozilla.org\":\"0a908074-eb8b-40b4-8ed4-4fa9f01bbf2e\",\"twitter@search.mozilla.org\":\"bc9613ee-7ab7-497d-ad10-87c545e8841c\",\"wikipedia@search.mozilla.org\":\"482fa431-7004-4fe0-8a98-aa88b63f73ec\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1571572189);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp-manager.buildID", "20191002193559");
user_pref("media.gmp-manager.lastCheck", 1571572186);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "38258ebf-d120-4804-9c03-bc6890ff13aa");
user_pref("security.sandbox.plugin.tempDirSuffix", "6ff052cf-24c3-4481-8853-841d167130b4");
user_pref("services.blocklist.pinning.checked", 1571572166);
user_pref("services.settings.clock_skew_seconds", 20);
user_pref("services.settings.last_etag", "\"1571529674307\"");
user_pref("services.settings.last_update_seconds", 1571572166);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1571572166);
user_pref("services.settings.main.cfr-fxa.last_check", 1571572166);
user_pref("services.settings.main.cfr.last_check", 1571572166);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1571572166);
user_pref("services.settings.main.hijack-blocklists.last_check", 1571572166);
user_pref("services.settings.main.language-dictionaries.last_check", 1571572166);
user_pref("services.settings.main.normandy-recipes.last_check", 1571572166);
user_pref("services.settings.main.sites-classification.last_check", 1571572166);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1571572166);
user_pref("services.settings.security.onecrl.checked", 1571572166);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1571573768);
user_pref("toolkit.telemetry.cachedClientID", "cfa41286-fb4b-435d-97a3-411491e72ec5");
user_pref("toolkit.telemetry.previousBuildID", "20191002193559");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
